sudo: required
services:
  - docker


before_install:
  - docker build -t mohanchoudary/docker-react -f Dockerfile.dev .

script:
  - docker run mohanchoudary/docker-react npm run test -- -- coverage
